### ISSUE TITLE
Difference in behavior depending on version of Git installed

### ISSUE THREAD

**Issue by jrick** [Masterminds/vcs#11] opened 2015-12-30 20:00 UTC
Continuing with our work to get glide working on Windows, @davecgh and I noticed that the identical commands were producing different results, with mine working and his failing.  We believe the root cause of this issue is the differences in our git installs.  I use http://git-for-windows.github.io/ while he is using git installed through msys2's pacman.  My git understands Windows paths, while his does not.

When this vcs package makes a call to, e.g. clone a git repo, it appends the local path as the last argument of the command.  On windows, this will be a windows path.  This works with my git, but his throws errors such as:

```
[WARN] Update failed for github.com/btcsuite/btclog: fatal: could not create work tree dir 'D:\tmpgo\src\github.com\btcsuite\btcd\vendor\github.com\btcsuite\btclog': No such file or directory : exit status 128
```

which appears to be from git's stderr.

We took a look at how go (the tool) itself handled this when exec'ing git for 'go get' commands.  They don't add the local path to the end of the arguments at all and instead change the relative directory:

https://github.com/golang/go/blob/e35901fd65a9c0f475de260a79b7b628d9d07ebf/src/cmd/go/vcs.go#L345-L347

**Comment by davecgh** [comment] 2015-12-30 20:38
In order to prove whether or not this is the issue, I made the following extremely hacky changes.  Clearly this is not the really the right way to fix it ultimately as it's not agnostic to the command, but it shows that it is in fact the issue:

```diff
diff --git a/repo.go b/repo.go
index 2bacc5a..a89569e 100644
--- a/repo.go
+++ b/repo.go
@@ -32,6 +32,7 @@ import (
        "log"
        "os"
        "os/exec"
+       "path/filepath"
        "regexp"
        "strings"
        "time"
@@ -189,7 +190,17 @@ func (b *base) setLocalPath(local string) {
 }

 func (b base) run(cmd string, args ...string) ([]byte, error) {
-       out, err := exec.Command(cmd, args...).CombinedOutput()
+       dir := "."
+       if len(args) > 2 {
+               dir = filepath.Dir(args[2])
+               if err := os.MkdirAll(dir, 0655); err != nil {
+                       return nil, err
+               }
+               args[2] = filepath.Base(args[2])
+       }
+       c := exec.Command(cmd, args...)
+       c.Dir = dir
+       out, err := c.CombinedOutput()
        b.log(out)
        if err != nil {
                err = fmt.Errorf("%s: %s", out, err)
```

With these changes (msys2 git under both msys2 bash+mintty and cmd.exe):

> $ glide up
> [INFO] Fetching updates for github.com/btcsuite/btclog.
> [INFO] Fetching updates for github.com/btcsuite/btcutil.
> ...
> [WARN] Problem setting version on github.com/btcsuite/btcd: chdir D:\Projects\mygo\src\github.com\btcsuite\btcd\vendor\github.com\btcsuite\btcd: The system cannot find the file specified. (flatten)
> [INFO] Project relies on 16 dependencies.
> [INFO] Writing glide.lock file

As you can see there is still another issue where it is trying to import the project itself, but that is not related to this issue.

**Comment by jrick** [comment] 2015-12-30 20:47
I tested glide patched with the above hack using git-for-windows and it still works.

**Comment by mattfarina** [comment] 2015-12-31 01:56
I think I understand the issue but there's a problem that still needs to be worked out.

Glide allows you to have a package path and repo that are different. So you can handle things like forks. You could the package `github.com/foo/bar` but actually get it from `github.com/me/bar`. You clone from one location and put it in the path location of the other. This is how we enable working with forks. The `golang.org/x/tools/go/vcs`, which is essentially what's used in the `go` tool, doesn't provide support to do things like this.

The VCS library is also a more general purpose library. People use it to checkout repos to many different locations. It's not just for working with `go get` like things.

How can we modify the behavior here while still keeping the feature of specifying the path?

Also, why doesn't git installed through msys2's pacman know how to handle Windows paths on Windows? Should a bug be filed someplace (or maybe it already exists)?

**Comment by jrick** [comment] 2015-12-31 02:10
Couldn't you just MkdirAll up through "github.com/foo" manually (I think vcs is already doing this), and then, from that new directory (setting the exec.Cmd.Dir field) execute the git/hg/bzr/... clone, which will create the bar directory from there?  The only other corner case I can see is when the clone url doesn't end in bar.  For that, you could specify the clone dir as a relative path at the end of the arguments  (just "bar" in this case) instead of the full (windows or unix-specific) path.

I don't think the issues with msys2 git is a bug per se, although I do find it unfortunate (and I switched away from msys2 git for that exact reason -- it was unusable with powershell's path tab completion).  It's just a straight unix port without any extra attention given to make it nice to use from the native windows shells.  All of the msys2 binaries are like that.

**Comment by jrick** [comment] 2015-12-31 02:14
Another possible option would be to MkdirAll the full package path, exec from it, and clone into `.`.

**Comment by davecgh** [comment] 2015-12-31 02:21
For reference:

```bash
$ mkdir -p /c/foo && cd /c/foo && git init && echo 'foo' > foo.txt && git add foo.txt && git commit -am "Initial commit"
Initialized empty Git repository in /c/foo/.git/
On branch master
nothing to commit, working directory clean
$  mkdir -p /c/foo2 && cd /c/foo2 && git clone /c/foo .
Cloning into '.'...
done.
```

However:
```bash
$  mkdir -p /c/foo3 && cd /c/foo3 && git clone 'C:\foo' .
Cloning into '.'...
fatal: '/c/foo3/C:\foo' does not appear to be a git repository
fatal: Could not read from remote repository.
```

So it's pretty clear that msys2 git installed by pacman does not accept Windows paths.

**Comment by davecgh** [comment] 2015-12-31 02:38
As far as a potential solution, I think you could probably just detect when the environment variable `MSYSTEM` is set (it can be different values depending on whether you're running an MSYS2 shell or a MinGW-w{64,32} shell, so just detecting if it's set to anything should suffice)  and convert the paths to unix paths before calling the vcs tool.

I realize that probably isn't the most beautiful solution, but it should do the trick and will allow glide to work under `cmd.exe`, `PowerShell`, `MinGW/MSYS`, and `MSYS2` which covers what I believe is the vast majority of Windows setups used by Go users.

**Comment by davecgh** [comment] 2015-12-31 02:40
@jrick I think the issue with that solution is the fact the `remote` parameter doesn't actually have to be a URL.  Obviously it will be in the vast majority of cases, but it is perfectly acceptable to do:

```bash
$ git clone /c/location1 /d/foo
```

**Comment by jrick** [comment] 2015-12-31 02:46
As silly as that is for a project as glide, it's still possible using file urls: `git clone file:///c:/location2 file:///d:/foo`.

**Comment by davecgh** [comment] 2015-12-31 02:47
Sure, but you can only set one working directory in the command.  So one or the other would fail.

**Comment by jrick** [comment] 2015-12-31 02:49
It could be a real solution that doesn't totally suck though.  Rewrite the local path as a file url instead of detecting a msys2 environment (which may not necessarily mean you're using msys2 git) and munging to a unix path.

**Comment by jrick** [comment] 2015-12-31 02:52
I should also mention that I have no idea if any of the other vcs's that this package works with allow that.

**Comment by davecgh** [comment] 2015-12-31 02:53
```bash
$ mkdir -p /c/foo && cd /c/foo && git init && echo 'foo' > foo.txt && git add foo.txt && git commit -m "Initial commit"
Initialized empty Git repository in /c/foo/.git/
...
$ mkdir -p /c/foo2 && cd /c/foo2 && git clone file://c:/foo .
Cloning into '.'...
fatal: '/foo' does not appear to be a git repository
fatal: Could not read from remote repository.
```bash

**Comment by jrick** [comment] 2015-12-31 02:54
three slashes before the drive.

**Comment by davecgh** [comment] 2015-12-31 02:56
```bash
$ mkdir -p /c/foo2 && cd /c/foo2 && git clone file:///c:/foo .
Cloning into '.'...
fatal: '/c:/foo' does not appear to be a git repository
-----
$ mkdir -p /c/foo2 && cd /c/foo2 && git clone file:///c/foo .
Cloning into '.'...
remote: Counting objects: 3, done.
```

The second one works, because I converted it to a unix path.

**Comment by jrick** [comment] 2015-12-31 02:57
Hmm, I guess that won't work in msys2 git then either.

**Comment by mattfarina** [comment] 2016-01-01 13:38
If the current codebase on this project were used by the path passed to it was relative would that work to fix the Glide issue on Windows?

**Comment by davecgh** [comment] 2016-01-05 16:17
I believe it would.  The root of the issue is passing absolute paths to git.  I should also note that it's not really the fault of glide either as passing an absolute Windows-style path to an application on a Windows platform really should work correctly.  Unfortunately, git (and some other apps) installed via pacman on MSYS2 (which is otherwise really nice) doesn't accept Windows-style paths.

**Comment by jrick** [comment] 2016-01-05 19:41
As long as glide isn't being configured to fetch from a local directory (in that case, there's no way to avoid platform-specific paths in the arguments), then changing the relative directory should work.

It's not a perfect solution given that limitation and how this is intended to be a general purpose package, but in the case of typical glide usage it should do the trick.

**Comment by aboukirev** [comment] 2016-03-10 14:54
What I would suggest is for initial clone make the working directory creation not a workaround but an unconditional first step, i.e. ensure that respective target folder under `vendor` exists.  It won't hurt anything.
The next change I would do is parameterize `runFromDir` in `repo.go` by passing an additional directory argument.  In most cases it will be `local` property of the repository.  However, for the initial clone pass `basePath`.
And then, finally, you don't need to pass full target clone path anymore to the command itself because it will be run inside`basePath` and will take the last part of the repository URL as a folder relative to `basePath`.  Moreover, there will be no os-specific path separators in the command arguments anymore.
Hope this makes sense.

**Comment by mattfarina** [comment] 2016-03-15 15:34
If I understand this right, the issue is in Glide in that it passes in absolute paths. Relative paths work but absolute paths are an issue. Is that right? So, if Glide passed relative paths to `vcs` this problem would go away?

**Comment by jrick** [comment] 2016-03-15 16:16
It can still use relative paths (e.g. `git clone https://github.com/some/forkedrepo repo`, which uses the relative path `repo`) , but the relative path can't contain any windows path separators or it will fail to work in msys2 git (and perhaps other ports as well, except with git-for-windows which handles these correctly).  The only remaining issue I see is when the clone url is not a url but another filepath, then it becomes impossible to use a path (absolute or relative).  I don't know of any solution to this issue other than "use git-for-windows because it's not broken".

Another possibility may be to use relative paths and rewrite the windows path separators with unix ones.  I believe all the git ports still understand unix paths just fine.  However this is a git-specific hack and I'm unsure how it would affect any of the other vcs tools this package needs to work with.

**Comment by davecgh** [comment] 2016-03-15 16:38
I was digging into this a bit more and it seems that root of the issue is it fails with Windows paths under msys2 git only if the destination directory hasn't been created.

For example, the following extremely simply program which just clones the glide repository, when run under msys2 with `git 2.6.3-1` installed by its package manager, shows the problem:

```Go
package main

import (
	"fmt"
	"os"
	"os/exec"
)

func main() {
	cmd := exec.Command("git", "clone", "https://github.com/Masterminds/glide", `D:\path\to\glide`)
	output, err := cmd.CombinedOutput()
	if err != nil {
		fmt.Printf("%s\n", output)
		os.Exit(1)
	}
	fmt.Printf("%s\n", output)
}
```

```bash
$ go run main.go
fatal: could not create work tree dir 'D:\path\to\glide': No such file or directory
```

With a small change to create the parent directory in the code first, it works properly:

```Go
package main

import (
	"fmt"
	"os"
	"os/exec"
)

func main() {
	if err := os.MkdirAll(`D:\path\to`, 0755); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	cmd := exec.Command("git", "clone", "https://github.com/Masterminds/glide", `D:\path\to\glide`)
	output, err := cmd.CombinedOutput()
	if err != nil {
		fmt.Printf("%s\n", output)
		os.Exit(1)
	}
	fmt.Printf("%s\n", output)
}
```

Output:

```bash
$ go run main.go
Cloning into 'glide'...
$ ls -al /c/path/to/glide
total 93K
...
```

All of that said, I agree with @aboukirev here in that it would be better parameterize the run function to accept the directory, and then set the current working directory to it like the `go` tool does in order to remove the need for specifying the absolute path altogether.  Modifying the same example like this would yield:

```Go
package main

import (
	"fmt"
	"os"
	"os/exec"
)

func main() {
	parentPath := `D:\path\to`
	if err := os.MkdirAll(parentPath, 0755); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	cmd := exec.Command("git", "clone", "https://github.com/Masterminds/glide", "glide")
	cmd.Dir = parentPath
	output, err := cmd.CombinedOutput()
	if err != nil {
		fmt.Printf("%s\n", output)
		os.Exit(1)
	}
	fmt.Printf("%s\n", output)
}
$ ls -al /c/path/to/glide
total 93K
...
```

**Comment by mattfarina** [comment] 2016-03-17 18:44
@davecgh @jrick Here is my confusion...

1. When you perform a `Get` for Git the `run` method does take [the local location](https://github.com/Masterminds/vcs/blob/5ae1b36588ccd3c2dc8aa4c1e7e0cd4a06f8a7ee/git.go#L66) to clone it into. This location can be relative or absolute. The difference between relative and absolute has to do with the calling codebase. This issue is on Masterminds/vcs. The calling code, that passes in the path, is Glide. _Does that mean the issue is in Glide and not in Masterminds/vcs?_
2. Most of the time Git is able to create the directory and any needed parents. Git is smart about creating these directories when it can and only does it if the repo can be cloned. So, most Git errors don't result in the directory tree being created. My attempt has been to preserve that. So, `vcs` tries to do a normal Git clone. [If that fails and the reason is that it's unable to create the directory it then creates it manually and tries again](https://github.com/Masterminds/vcs/blob/5ae1b36588ccd3c2dc8aa4c1e7e0cd4a06f8a7ee/git.go#L71). This stops other errors from leaving orphaned directories around. _Is there a problem with this approach that currently sits on master?_

Thanks for continuing to poke at this.

**Comment by jrick** [comment] 2016-03-21 15:23
Glide is using absolute filepaths here, but I don't believe that switching to a relative path (relative to glide's current working directory) will work either, because relative paths will still include backslashes in them.  In order to avoid backslashes, the command would need to run in the parent directory of the cloned git repo, so that the relative path would just be the folder name of the repo.

Regarding the second point, I don't have msys2 git installed on any of my boxes, so I can't test that out (the error is never hit, because git-for-windows does understand the backslashes when it must create the directory).  @davecgh can you test this?

**Comment by mattfarina** [comment] 2016-03-22 16:39
I understand the problem more thoroughly now and have looked at how `go` is doing it. The issue is in Glide in the way it's passing information in. This package can be used for many things and Glide is just one of them. With that, I want to continue this work on Masterminds/glide#206 and I've scheduled it for version 0.11.

With that I'm closing this issue. Thanks for helping me understand the problem.

**Closed by mattfarina** 2016-03-22 16:39 UTC
